### ISSUE TITLE
support asciimath input?

### ISSUE THREAD

**Issue by masx200** [nickgirardo/mathjax-loader#1]
support asciimath input?

http://asciimath.org/

**Comment by nickgirardo** [comment]
This looks like it should be possible, I can look into this tonight

**Comment by nickgirardo** [comment]
Ok, AsciiMath should be supported in the newly published version `0.2.0`.  See #2 

I'm not too familiar with AsciiMath but it looks like it's working fine.  If you run into any issues or if you have any ideas for test cases to look out for (I'm not familiar with anything that would be a syntax error in AsciiMath for instance), please let me know!

**Comment by masx200** [comment]
https://github.com/mathjax/MathJax-demos-node/blob/master/direct/am2chtml

https://github.com/mathjax/MathJax-demos-node/blob/master/direct/mml2svg
